### ISSUE TITLE
Json in body

### ISSUE THREAD

**Issue by federicolucca** [solso/source2swagger#17]
Hi,

Very good work! i am working on a my api documentation. I need to put some json code in the body,like example. how can i do?  

##~ o = a.operations.add 
##~ o.set :httpMethod => "POST", :summary => "Returns all of the foos.", :deprecated => false, :nickname => "test"
##~ p = o.parameters.add
##~ p.set :name => "body", :dataType => "String" ,:required => true

Thank in advance
Federico

**Comment by solso** [comment]
hi @federicolucca , you will send the json object encoded as a string, so why do you use the :dataType => String

I  do not know if the evolution of swagger spec is proving additional dataType, if so, try just to change the type "String" to whatever dataType is available, that should do the trick. The source2swagger is just a "half-assed"  way to declare a swagger spec, which is basically a json object with the grammar.

hope it helps,

**Comment by federicolucca** [comment]
Thanks a lot!!! i resolved like this example
##~ signup = {:id => "Signup", :properties => {:email => {:type => "string"}, :device => {:type => "string"}, :id => {:type => "string"}, :name => {:type => "string"}, :surname => {:type => "string"}}}
##~ s.models = {"SignUp" => signup}
##~ p.set :name => "body", :dataType => "SignUp" ,:paramType => "body" ,:required => true

thanks again
